# types = {
#     "integer": "int",
#     "text": "str",
#     "boolean": "bool",
#     "smallint": "int",
#     "resources": "Resources",
#     "numeric": "decimal.Decimal",
#     "timestamp with time zone": "datetime.datetime",
#     "bigint": "int",
#     "GENERATED BY DEFAULT AS IDENTITY": "int",
#     "interval": "datetime.timedelta",
#     "json": dict[str, Any],
# }


# def table(text: str) -> None:
#     lines = [i.strip() for i in text.split(",")]
#     lines = [i.split('"') for i in lines]
#     for line in lines:
#         if line[2].endswith("[]"):
#             print(f"    {line[1]}: list[{types.get(line[2].strip()[:-2], 'UNKNOWN')}]")
#         else:
#             print(f"    {line[1]}: {types.get(line[2].strip(), 'UNKNOWN')}")
