[tool.black]
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | venv
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | __pycache__
  | .VSCodeCounter
)/
'''

[tool.isort]
profile = "black"

[tool.pyright]
reportMissingTypeStubs = false
reportImportCycles = false
typeCheckingMode = "strict"
